replicaCount: 3

image:
  repository: jayjuhoonchoi/devops-journey
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 5000

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

env:
  APP_ENV: "production"
  APP_VERSION: "1.0.0"
  AUTHOR: "Jay Choi"
